pip install -e /Users/peterzhang/dev/github/PaddleSpeech
ERROR: Could not find a version that satisfies the requirement nara_wpe (from paddlespeech) (from versions: none)
Obtaining file:///Users/peterzhang/dev/github/PaddleSpeech
Collecting editdistance
  Downloading editdistance-0.6.0-cp39-cp39-macosx_10_9_x86_64.whl (21 kB)
Collecting g2p_en
  Downloading g2p_en-2.1.0-py3-none-any.whl (3.1 MB)
Collecting g2pM
  Downloading g2pM-0.1.2.5-py3-none-any.whl (1.7 MB)
Collecting h5py
  Downloading h5py-3.7.0-cp39-cp39-macosx_10_9_x86_64.whl (3.2 MB)
Collecting inflect
  Downloading inflect-5.6.0-py3-none-any.whl (33 kB)
Collecting jieba
  Downloading jieba-0.42.1.tar.gz (19.2 MB)
Collecting jsonlines
  Downloading jsonlines-3.0.0-py3-none-any.whl (8.5 kB)
Collecting kaldiio
  Downloading kaldiio-2.17.2.tar.gz (24 kB)
Collecting librosa==0.8.1
  Downloading librosa-0.8.1-py3-none-any.whl (203 kB)
Collecting loguru
  Downloading loguru-0.6.0-py3-none-any.whl (58 kB)
Collecting matplotlib
  Downloading matplotlib-3.5.2-cp39-cp39-macosx_10_9_x86_64.whl (7.3 MB)

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/nara-wpe/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x102787a00>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/nara-wpe/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x102787bb0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/nara-wpe/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x102787d60>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/nara-wpe/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x102787f10>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/nara-wpe/
ERROR: Could not find a version that satisfies the requirement nara_wpe (from paddlespeech) (from versions: none)
ERROR: No matching distribution found for nara_wpe
WARNING: You are using pip version 21.1.2; however, version 22.1.2 is available.
You should consider upgrading via the '/Users/peterzhang/dev/github/PaddleSpeech/venv/bin/python -m pip install --upgrade pip' command.

paddlespeech_server start --config_file ./paddlespeech/server/conf/application.yaml
/opt/conda/lib/python3.9/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...

paddlespeech_server start --config_file ./paddlespeech/server/conf/application.yaml
/opt/conda/lib/python3.9/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package cmudict to /root/nltk_data...
[nltk_data]   Unzipping corpora/cmudict.zip.
INFO 2022-06-20 07:38:42,545 font_manager.py:1443] generated new fontManager
/opt/conda/lib/python3.9/site-packages/pip/_vendor/packaging/version.py:111: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
/opt/conda/lib/python3.9/site-packages/pip/_vendor/packaging/version.py:111: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
/opt/conda/lib/python3.9/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  warnings.warn(
/opt/conda/lib/python3.9/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
  warnings.warn(
/opt/conda/lib/python3.9/site-packages/setuptools/config.py:510: DeprecationWarning: The license_file parameter is deprecated, use license_files instead.
  warnings.warn(msg, warning_class)
Collecting paddlespeech_ctcdecoders
  Downloading paddlespeech_ctcdecoders-0.2.1-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (16.9 MB)
     |███▎                            | 1.7 MB 21 kB/s eta 0:11:51
     |█████████▊                      | 5.1 MB 30 kB/s eta 0:06:20